### ISSUE TITLE
应该提供docker方式配置服务端

### ISSUE THREAD

**Issue by 8debug** [heruijun/FlutterFrom0To1#5]
可以考虑利用docker方式配置服务端，让读者能更快的专注flutter的学习开发。

如果一个移动端实战类教程会耗费较多时间在后端环境搭建上，读者可能就会考虑换一个教程了。

**Comment by LaoXiZi** [comment]
我，两天了没把数据弄好...

**Comment by LaoXiZi** [comment]
PS D:\Develop\nodejs\Server\flutter-practice-server\server> npm install --registry=https://registry.npm.taobao.org
npm WARN eslint-plugin-vue@4.7.1 requires a peer of eslint@^3.18.0 || ^4.0.0 but none is installed. You must install peer dependencies yourself.

up to date in 10.767s
PS D:\Develop\nodejs\Server\flutter-practice-server\server> npm config set puppeteer_download_host=https://npm.taobao.org/mirrors
PS D:\Develop\nodejs\Server\flutter-practice-server\server>  npm i puppeteer
npm WARN rollback Rolling back puppeteer@1.20.0 failed (this is probably harmless): EBUSY: resource busy or locked, rmdir 'D:\Develop\nodejs\Server\flutter-practice-server\node_modules\puppeteer\.local-chromium\win64-686378\chrome-win'
npm WARN eslint-plugin-vue@4.7.1 requires a peer of eslint@^3.18.0 || ^4.0.0 but none is installed. You must install peer dependencies yourself.

npm ERR! path D:\Develop\nodejs\Server\flutter-practice-server\node_modules\puppeteer
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall rename
npm ERR! Error: EPERM: operation not permitted, rename 'D:\Develop\nodejs\Server\flutter-practice-server\node_modules\puppeteer' -> 'D:\Develop\nodejs\Server\flutter-practice-server\node_modules\.puppeteer.DELETE'
npm ERR!  { Error: EPERM: operation not permitted, rename 'D:\Develop\nodejs\Server\flutter-practice-server\node_modules\puppeteer' -> 'D:\Develop\nodejs\Server\flutter-practice-server\node_modules\.puppeteer.DELETE'
npm ERR!   cause:
npm ERR!    { Error: EPERM: operation not permitted, rename 'D:\Develop\nodejs\Server\flutter-practice-server\node_modules\puppeteer' -> 'D:\Develop\nodejs\Server\flutter-practice-server\node_modules\.puppeteer.DELETE'
npm ERR!      errno: -4048,
npm ERR!      code: 'EPERM',
npm ERR!      syscall: 'rename',
npm ERR!      path: 'D:\\Develop\\nodejs\\Server\\flutter-practice-server\\node_modules\\puppeteer',
npm ERR!      dest: 'D:\\Develop\\nodejs\\Server\\flutter-practice-server\\node_modules\\.puppeteer.DELETE' },
npm ERR!   stack: 'Error: EPERM: operation not permitted, rename \'D:\\Develop\\nodejs\\Server\\flutter-practice-server\\node_modules\\puppeteer\' -> \'D:\\Develop\\nodejs\\Server\\flutter-practice-server\\node_modules\\.puppeteer.DELETE\'',
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'rename',
npm ERR!   path: 'D:\\Develop\\nodejs\\Server\\flutter-practice-server\\node_modules\\puppeteer',
npm ERR!   dest: 'D:\\Develop\\nodejs\\Server\\flutter-practice-server\\node_modules\\.puppeteer.DELETE',
npm ERR!   parent: 'flutter-boss-server' }
npm ERR!
npm ERR! The operation was rejected by your operating system.
npm ERR! It's possible that the file was already in use (by a text editor or antivirus),
npm ERR! or that you lack permissions to access it.
npm ERR!
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator (though this is not recommended).

npm ERR! A complete log of this run can be found in:
npm ERR!     D:\Develop\nodejs\node_cache\_logs\2020-04-25T01_14_05_595Z-debug.log
PS D:\Develop\nodejs\Server\flutter-practice-server\server> npm config set puppeteer_download_host=https://npm.taobao.org/mirrors
PS D:\Develop\nodejs\Server\flutter-practice-server\server>  npm i puppeteer
Downloading Chromium r686378 - 143 Mb [====================] 100% 0.0s
Chromium downloaded to D:\Develop\nodejs\Server\flutter-practice-server\node_modules\puppeteer\.local-chromium\win64-686378ode install.js
npm WARN eslint-plugin-vue@4.7.1 requires a peer of eslint@^3.18.0 || ^4.0.0 but none is installed. You must install peer dependencies yourself.

+ puppeteer@1.20.0
added 2 packages from 3 contributors and updated 1 package in 32.93s
PS D:\Develop\nodejs\Server\flutter-practice-server\server> node-v
node-v : 无法将“node-v”项识别为 cmdlet、函数、脚本文件或可运行程序的名称。请检查名称的拼写，如果包括路径，请确保路径
正确，然后再试一次。
所在位置 行:1 字符: 1
+ node-v
+ ~~~~~~
    + CategoryInfo          : ObjectNotFound: (node-v:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PS D:\Develop\nodejs\Server\flutter-practice-server\server> node -v
v8.12.0
PS D:\Develop\nodejs\Server\flutter-practice-server\server> npm run dev

> flutter-boss-server@1.0.0 dev D:\Develop\nodejs\Server\flutter-practice-server
> cross-env NODE_ENV=development nodemon server/index.js --watch server

[nodemon] 1.19.4
[nodemon] to restart at any time, enter `rs`
[nodemon] watching dir(s): server\**\*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node server/index.js`
i Preparing project for development                                                                           09:18:53
i Initial build may take a while                                                                              09:18:53
√ Builder initialized                                                                                         09:18:53
√ Nuxt files generated                                                                                        09:18:53


√ Client
  Compiled successfully in 6.62s

√ Server
  Compiled successfully in 5.33s

i Waiting for file changes                                                                                    09:19:01
(node:7204) DeprecationWarning: current URL string parser is deprecated, and will be removed in a future version. To use the new parser, pass option { useNewUrlParser: true } to MongoClient.connect.
(node:7204) DeprecationWarning: current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.
MongoDB Connected successfully!
Mongoose: companies.ensureIndex({ id: 1 }, { unique: true, background: true })
Mongoose: companydetails.ensureIndex({ id: 1 }, { unique: true, background: true })
Mongoose: jobs.ensureIndex({ id: 1 }, { unique: true, background: true })
Mongoose: messages.ensureIndex({ id: 1 }, { unique: true, background: true })
Mongoose: users.ensureIndex({ username: 1 }, { unique: true, background: true })
(node:7204) DeprecationWarning: collection.ensureIndex is deprecated. Use createIndexes instead.
Mongoose: users.findOne({ username: 'flutter' }, { projection: {} })
Mongoose: users.ensureIndex({ email: 1 }, { unique: true, background: true })

 READY  Server listening on http://192.168.2.106:3000                                                         09:19:01

events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 192.168.2.106:3000
    at Server.setupListenHandle [as _listen2] (net.js:1360:14)
    at listenInCluster (net.js:1401:12)
    at doListen (net.js:1510:7)
    at _combinedTickCallback (internal/process/next_tick.js:142:11)
    at process._tickDomainCallback (internal/process/next_tick.js:219:9)
[nodemon] app crashed - waiting for file changes before starting...
[nodemon] restarting due to changes...
[nodemon] starting `node server/index.js`
i Preparing project for development                                                                           09:19:47
i Initial build may take a while                                                                              09:19:47
√ Builder initialized                                                                                         09:19:47
√ Nuxt files generated                                                                                        09:19:47


√ Client
  Compiled successfully in 5.27s

√ Server
  Compiled successfully in 4.23s

i Waiting for file changes                                                                                    09:19:53
(node:12536) DeprecationWarning: current URL string parser is deprecated, and will be removed in a future version. To use the new parser, pass option { useNewUrlParser: true } to MongoClient.connect.
(node:12536) DeprecationWarning: current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.
MongoDB Connected successfully!
Mongoose: companies.ensureIndex({ id: 1 }, { unique: true, background: true })
Mongoose: companydetails.ensureIndex({ id: 1 }, { unique: true, background: true })
Mongoose: jobs.ensureIndex({ id: 1 }, { unique: true, background: true })
Mongoose: messages.ensureIndex({ id: 1 }, { unique: true, background: true })
Mongoose: users.ensureIndex({ username: 1 }, { unique: true, background: true })
(node:12536) DeprecationWarning: collection.ensureIndex is deprecated. Use createIndexes instead.
Mongoose: users.findOne({ username: 'flutter' }, { projection: {} })
Mongoose: users.ensureIndex({ email: 1 }, { unique: true, background: true })

 READY  Server listening on http://192.168.2.106:3000                                                         09:19:53

Mongoose: users.ensureIndex({ password: 1 }, { unique: true, background: true })
[nodemon] restarting due to changes...
[nodemon] starting `node server/index.js`
i Preparing project for development                                                                           09:19:57
i Initial build may take a while                                                                              09:19:57
√ Builder initialized                                                                                         09:19:57
√ Nuxt files generated                                                                                        09:19:57


√ Client
  Compiled successfully in 5.15s

√ Server
  Compiled successfully in 4.12s

i Waiting for file changes                                                                                    09:20:03
(node:12476) DeprecationWarning: current URL string parser is deprecated, and will be removed in a future version. To use the new parser, pass option { useNewUrlParser: true } to MongoClient.connect.
(node:12476) DeprecationWarning: current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.
MongoDB Connected successfully!
Mongoose: companies.ensureIndex({ id: 1 }, { unique: true, background: true })
Mongoose: companydetails.ensureIndex({ id: 1 }, { unique: true, background: true })
Mongoose: jobs.ensureIndex({ id: 1 }, { unique: true, background: true })
Mongoose: messages.ensureIndex({ id: 1 }, { unique: true, background: true })
Mongoose: users.ensureIndex({ username: 1 }, { unique: true, background: true })
(node:12476) DeprecationWarning: collection.ensureIndex is deprecated. Use createIndexes instead.
Mongoose: users.findOne({ username: 'flutter' }, { projection: {} })
Mongoose: users.ensureIndex({ email: 1 }, { unique: true, background: true })

 READY  Server listening on http://192.168.2.106:3000                                                         09:20:04

Mongoose: companies.find({}, { projection: {} })
Mongoose: users.ensureIndex({ password: 1 }, { unique: true, background: true })
正在抓取职位列表页面
正在抓取公司列表页面
[ { id: '', inc: undefined, tagsResult: [], companyImgsResult: [] } ]
Mongoose: companydetails.findOne({ id: '' }, { projection: {} })
null
(node:5588) UnhandledPromiseRejectionWarning: TimeoutError: Navigation Timeout Exceeded: 30000ms exceeded
    at Promise.then (D:\Develop\nodejs\Server\flutter-practice-server\node_modules\puppeteer\lib\LifecycleWatcher.js:142:21)
    at <anonymous>
  -- ASYNC --
    at Frame.<anonymous> (D:\Develop\nodejs\Server\flutter-practice-server\node_modules\puppeteer\lib\helper.js:111:15)
    at Page.goto (D:\Develop\nodejs\Server\flutter-practice-server\node_modules\puppeteer\lib\Page.js:674:49)
    at Page.<anonymous> (D:\Develop\nodejs\Server\flutter-practice-server\node_modules\puppeteer\lib\helper.js:112:23)
    at fetchCompanyList (D:\Develop\nodejs\Server\flutter-practice-server\server\crawler\company-list.js:10:14)
    at D:\Develop\nodejs\Server\flutter-practice-server\server\crawler\company-list.js:58:22
    at <anonymous>
(node:5588) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:5588) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:2560) UnhandledPromiseRejectionWarning: TimeoutError: Navigation Timeout Exceeded: 30000ms exceeded
    at Promise.then (D:\Develop\nodejs\Server\flutter-practice-server\node_modules\puppeteer\lib\LifecycleWatcher.js:142:21)
    at <anonymous>
  -- ASYNC --
    at Frame.<anonymous> (D:\Develop\nodejs\Server\flutter-practice-server\node_modules\puppeteer\lib\helper.js:111:15)
    at Page.goto (D:\Develop\nodejs\Server\flutter-practice-server\node_modules\puppeteer\lib\Page.js:674:49)
    at Page.<anonymous> (D:\Develop\nodejs\Server\flutter-practice-server\node_modules\puppeteer\lib\helper.js:112:23)
    at fetchJobList (D:\Develop\nodejs\Server\flutter-practice-server\server\crawler\job-list.js:10:14)
    at D:\Develop\nodejs\Server\flutter-practice-server\server\crawler\job-list.js:68:18
    at <anonymous>
(node:2560) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:2560) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Mongoose: companies.count({}, {})
(node:12476) DeprecationWarning: collection.count is deprecated, and will be removed in a future version. Use Collection.countDocuments or Collection.estimatedDocumentCount instead
Mongoose: companies.find({}, { sort: { 'meta.createdAt': -1 }, skip: 0, limit: 10, projection: {} })
[nodemon] restarting due to changes...
[nodemon] starting `node server/index.js`
i Preparing project for development                                                                           09:20:52
i Initial build may take a while                                                                              09:20:52
√ Builder initialized                                                                                         09:20:52
√ Nuxt files generated                                                                                        09:20:52


√ Client
  Compiled successfully in 5.25s

√ Server
  Compiled successfully in 4.23s

i Waiting for file changes                                                                                    09:20:58
(node:8128) DeprecationWarning: current URL string parser is deprecated, and will be removed in a future version. To use the new parser, pass option { useNewUrlParser: true } to MongoClient.connect.
(node:8128) DeprecationWarning: current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.
MongoDB Connected successfully!
Mongoose: companies.ensureIndex({ id: 1 }, { unique: true, background: true })
Mongoose: companydetails.ensureIndex({ id: 1 }, { unique: true, background: true })
Mongoose: jobs.ensureIndex({ id: 1 }, { unique: true, background: true })
Mongoose: messages.ensureIndex({ id: 1 }, { unique: true, background: true })
Mongoose: users.ensureIndex({ username: 1 }, { unique: true, background: true })
(node:8128) DeprecationWarning: collection.ensureIndex is deprecated. Use createIndexes instead.
Mongoose: users.findOne({ username: 'flutter' }, { projection: {} })
Mongoose: users.ensureIndex({ email: 1 }, { unique: true, background: true })

 READY  Server listening on http://172.20.10.3:3000                                                           09:20:59

events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRNOTAVAIL 172.20.10.3:3000
    at Server.setupListenHandle [as _listen2] (net.js:1343:19)
    at listenInCluster (net.js:1401:12)
    at doListen (net.js:1510:7)
    at _combinedTickCallback (internal/process/next_tick.js:142:11)
    at process._tickDomainCallback (internal/process/next_tick.js:219:9)
[nodemon] app crashed - waiting for file changes before starting...
[nodemon] restarting due to changes...
[nodemon] starting `node server/index.js`
i Preparing project for development                                                                           09:21:16
i Initial build may take a while                                                                              09:21:16
√ Builder initialized                                                                                         09:21:16
√ Nuxt files generated                                                                                        09:21:16


√ Client
  Compiled successfully in 5.25s

√ Server
  Compiled successfully in 4.20s

i Waiting for file changes                                                                                    09:21:22
(node:12656) DeprecationWarning: current URL string parser is deprecated, and will be removed in a future version. To use the new parser, pass option { useNewUrlParser: true } to MongoClient.connect.
(node:12656) DeprecationWarning: current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.
MongoDB Connected successfully!
Mongoose: companies.ensureIndex({ id: 1 }, { unique: true, background: true })
Mongoose: companydetails.ensureIndex({ id: 1 }, { unique: true, background: true })
Mongoose: jobs.ensureIndex({ id: 1 }, { unique: true, background: true })
Mongoose: messages.ensureIndex({ id: 1 }, { unique: true, background: true })
Mongoose: users.ensureIndex({ username: 1 }, { unique: true, background: true })
(node:12656) DeprecationWarning: collection.ensureIndex is deprecated. Use createIndexes instead.
Mongoose: users.findOne({ username: 'flutter' }, { projection: {} })
Mongoose: users.ensureIndex({ email: 1 }, { unique: true, background: true })

 READY  Server listening on http://172.20.10.3:3000                                                           09:21:22

events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRNOTAVAIL 172.20.10.3:3000
    at Server.setupListenHandle [as _listen2] (net.js:1343:19)
    at listenInCluster (net.js:1401:12)
    at doListen (net.js:1510:7)
    at _combinedTickCallback (internal/process/next_tick.js:142:11)
    at process._tickDomainCallback (internal/process/next_tick.js:219:9)
[nodemon] app crashed - waiting for file changes before starting...
[nodemon] restarting due to changes...
[nodemon] starting `node server/index.js`
i Preparing project for development                                                                           09:21:33
i Initial build may take a while                                                                              09:21:33
√ Builder initialized                                                                                         09:21:33
√ Nuxt files generated                                                                                        09:21:33


√ Client
  Compiled successfully in 5.44s

√ Server
  Compiled successfully in 4.36s

i Waiting for file changes                                                                                    09:21:39
(node:12424) DeprecationWarning: current URL string parser is deprecated, and will be removed in a future version. To use the new parser, pass option { useNewUrlParser: true } to MongoClient.connect.
(node:12424) DeprecationWarning: current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.
MongoDB Connected successfully!
Mongoose: companies.ensureIndex({ id: 1 }, { unique: true, background: true })
Mongoose: companydetails.ensureIndex({ id: 1 }, { unique: true, background: true })
Mongoose: jobs.ensureIndex({ id: 1 }, { unique: true, background: true })
Mongoose: messages.ensureIndex({ id: 1 }, { unique: true, background: true })
Mongoose: users.ensureIndex({ username: 1 }, { unique: true, background: true })
(node:12424) DeprecationWarning: collection.ensureIndex is deprecated. Use createIndexes instead.
Mongoose: users.findOne({ username: 'flutter' }, { projection: {} })
Mongoose: users.ensureIndex({ email: 1 }, { unique: true, background: true })

 READY  Server listening on http://172.20.10.3:3000                                                           09:21:40

events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRNOTAVAIL 172.20.10.3:3000
    at Server.setupListenHandle [as _listen2] (net.js:1343:19)
    at listenInCluster (net.js:1401:12)
    at doListen (net.js:1510:7)
    at _combinedTickCallback (internal/process/next_tick.js:142:11)
    at process._tickDomainCallback (internal/process/next_tick.js:219:9)
[nodemon] app crashed - waiting for file changes before starting...
[nodemon] restarting due to changes...
[nodemon] starting `node server/index.js`
i Preparing project for development                                                                           09:21:51
i Initial build may take a while                                                                              09:21:51
√ Builder initialized                                                                                         09:21:51
√ Nuxt files generated                                                                                        09:21:51


√ Client
  Compiled successfully in 5.19s

√ Server
  Compiled successfully in 4.17s

i Waiting for file changes                                                                                    09:21:57
(node:9948) DeprecationWarning: current URL string parser is deprecated, and will be removed in a future version. To use the new parser, pass option { useNewUrlParser: true } to MongoClient.connect.
(node:9948) DeprecationWarning: current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.
MongoDB Connected successfully!
Mongoose: companies.ensureIndex({ id: 1 }, { unique: true, background: true })
Mongoose: companydetails.ensureIndex({ id: 1 }, { unique: true, background: true })
Mongoose: jobs.ensureIndex({ id: 1 }, { unique: true, background: true })
Mongoose: messages.ensureIndex({ id: 1 }, { unique: true, background: true })
Mongoose: users.ensureIndex({ username: 1 }, { unique: true, background: true })
(node:9948) DeprecationWarning: collection.ensureIndex is deprecated. Use createIndexes instead.
Mongoose: users.findOne({ username: 'flutter' }, { projection: {} })
Mongoose: users.ensureIndex({ email: 1 }, { unique: true, background: true })

 READY  Server listening on http://192.168.2.106:3000                                                         09:21:57

Mongoose: companies.find({}, { projection: {} })
Mongoose: users.ensureIndex({ password: 1 }, { unique: true, background: true })
正在抓取职位列表页面
正在抓取公司列表页面
[ { id: '', inc: undefined, tagsResult: [], companyImgsResult: [] } ]
Mongoose: companydetails.findOne({ id: '' }, { projection: {} })
null
(node:3132) UnhandledPromiseRejectionWarning: TimeoutError: Navigation Timeout Exceeded: 30000ms exceeded
    at Promise.then (D:\Develop\nodejs\Server\flutter-practice-server\node_modules\puppeteer\lib\LifecycleWatcher.js:142:21)
    at <anonymous>
  -- ASYNC --
    at Frame.<anonymous> (D:\Develop\nodejs\Server\flutter-practice-server\node_modules\puppeteer\lib\helper.js:111:15)
    at Page.goto (D:\Develop\nodejs\Server\flutter-practice-server\node_modules\puppeteer\lib\Page.js:674:49)
    at Page.<anonymous> (D:\Develop\nodejs\Server\flutter-practice-server\node_modules\puppeteer\lib\helper.js:112:23)
    at fetchJobList (D:\Develop\nodejs\Server\flutter-practice-server\server\crawler\job-list.js:10:14)
    at D:\Develop\nodejs\Server\flutter-practice-server\server\crawler\job-list.js:68:18
    at <anonymous>
(node:3132) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:3132) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:9432) UnhandledPromiseRejectionWarning: TimeoutError: Navigation Timeout Exceeded: 30000ms exceeded
    at Promise.then (D:\Develop\nodejs\Server\flutter-practice-server\node_modules\puppeteer\lib\LifecycleWatcher.js:142:21)
    at <anonymous>
  -- ASYNC --
    at Frame.<anonymous> (D:\Develop\nodejs\Server\flutter-practice-server\node_modules\puppeteer\lib\helper.js:111:15)
    at Page.goto (D:\Develop\nodejs\Server\flutter-practice-server\node_modules\puppeteer\lib\Page.js:674:49)
    at Page.<anonymous> (D:\Develop\nodejs\Server\flutter-practice-server\node_modules\puppeteer\lib\helper.js:112:23)
    at fetchCompanyList (D:\Develop\nodejs\Server\flutter-practice-server\server\crawler\company-list.js:10:14)
    at D:\Develop\nodejs\Server\flutter-practice-server\server\crawler\company-list.js:58:22
    at <anonymous>
(node:9432) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:9432) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Mongoose: jobs.count({}, {})
(node:9948) DeprecationWarning: collection.count is deprecated, and will be removed in a future version. Use Collection.countDocuments or Collection.estimatedDocumentCount instead
Mongoose: jobs.find({}, { sort: { 'meta.createdAt': -1 }, skip: 0, limit: 10, projection: {} })
Mongoose: companies.count({}, {})
Mongoose: companies.find({}, { sort: { 'meta.createdAt': -1 }, skip: 0, limit: 10, projection: {} })
Mongoose: messages.find({}, { sort: { 'meta.createdAt': -1 }, projection: {} })

**Comment by LaoXiZi** [comment]
看着是数据抓取的时候出了问题

**Comment by 8debug** [comment]
这本书的服务端，我始终没有顺利的架设起来，采用爬虫的方式不是很灵活，时间一长容易失效
